### PR TITLE
Add Traefik + Let's Encrypt example

### PR DESCRIPTION
**Pull request by crazy-max**

### CODE REVIEW

**Comment by crazy-max** [comment]
Hi @eldada, can you give me some feedback about this PR please? Thanks!

**Comment by jainishshah17** [comment]
@crazy-max Can you please add little more details about Traefik + Let's Encrypt. For e.g Prerequisites and Advantages

**Comment by eldada** [comment]
Hey @crazy-max - as @jainishshah17 noted. Just add a some description of `Traefik` and `Let's Encrypt`.

**Comment by crazy-max** [comment]
@jainishshah17 @eldada Of course

**Comment by crazy-max** [comment]
@eldada Done, let me know if it's okay for you.

**Pull request merged**
